version: '3.8'

services:
  ollama:
    build: ./docker/ollama
    container_name: ollama-phi3
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: unless-stopped

  chroma:
    image: chromadb/chroma
    volumes:
      - ./chroma_data:/data
    ports:
      - "5000:8000"

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: fast_api
    ports:
      - "80:80"
    depends_on:
      - chroma
      - ollama
